/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     CLOCK_FREQ = 50000000
     MIN_MAX_DIFF = 500
     CENTER_WIDTH = 1500
     PERIOD = 20000
     RESOLUTION = 16
*/
module servo_2 (
    input clk,
    input rst,
    input [15:0] position,
    output reg servo
  );
  
  localparam CLOCK_FREQ = 26'h2faf080;
  localparam MIN_MAX_DIFF = 9'h1f4;
  localparam CENTER_WIDTH = 11'h5dc;
  localparam PERIOD = 15'h4e20;
  localparam RESOLUTION = 5'h10;
  
  
  localparam TOP = 41'h000000f4240;
  
  localparam MIN_MAX = 35'h0000061a8;
  
  localparam SHIFT = 6'h00;
  
  localparam OFFSET = 38'h000000a4f8;
  
  reg [15:0] M_pos_d, M_pos_q = 1'h0;
  reg [19:0] M_ctr_d, M_ctr_q = 1'h0;
  
  always @* begin
    M_ctr_d = M_ctr_q;
    M_pos_d = M_pos_q;
    
    M_ctr_d = M_ctr_q + 1'h1;
    if (M_ctr_q == 42'h000000f423f) begin
      if (position > 36'h00000e1a8) begin
        M_pos_d = 36'h00000e1a8;
      end else begin
        if (position < 36'h000001e58) begin
          M_pos_d = 36'h000001e58;
        end else begin
          M_pos_d = position;
        end
      end
      M_ctr_d = 1'h0;
    end
    servo = (M_pos_q << 6'h00) + 38'h000000a4f8 > M_ctr_q;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_pos_q <= 1'h0;
      M_ctr_q <= 1'h0;
    end else begin
      M_pos_q <= M_pos_d;
      M_ctr_q <= M_ctr_d;
    end
  end
  
endmodule
