/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [3:0] hdmi1_tmds,
    output reg [3:0] hdmi1_tmdsb
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_clk_wiz_CLK_OUT1;
  clk_wiz_v3_6 clk_wiz (
    .CLK_IN1(clk),
    .CLK_OUT1(M_clk_wiz_CLK_OUT1)
  );
  
  wire [1-1:0] M_hdmi_pclk;
  wire [4-1:0] M_hdmi_tmds;
  wire [4-1:0] M_hdmi_tmdsb;
  wire [1-1:0] M_hdmi_active;
  wire [11-1:0] M_hdmi_x;
  wire [10-1:0] M_hdmi_y;
  reg [8-1:0] M_hdmi_red;
  reg [8-1:0] M_hdmi_green;
  reg [8-1:0] M_hdmi_blue;
  hdmi_encoder_1 hdmi (
    .clk(M_clk_wiz_CLK_OUT1),
    .rst(1'h0),
    .red(M_hdmi_red),
    .green(M_hdmi_green),
    .blue(M_hdmi_blue),
    .pclk(M_hdmi_pclk),
    .tmds(M_hdmi_tmds),
    .tmdsb(M_hdmi_tmdsb),
    .active(M_hdmi_active),
    .x(M_hdmi_x),
    .y(M_hdmi_y)
  );
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_2 reset_cond (
    .clk(M_hdmi_pclk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    hdmi1_tmds = M_hdmi_tmds;
    hdmi1_tmdsb = M_hdmi_tmdsb;
    M_hdmi_red = M_hdmi_x[0+7-:8];
    M_hdmi_green = M_hdmi_y[0+7-:8];
    M_hdmi_blue = M_hdmi_x[0+7-:8] ^ M_hdmi_y[0+7-:8];
  end
endmodule
